'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,frameId='sour',lastDraft=null,lastEvaluation=null,lastSnapshot=null,busy=false;
const units={ml:'ml',dash:'dash',leaf:'片',sprig:'枝'};
const datasetNames={iba_official:'IBA 官方 · 本批快照',bar_assistant:'Bar Assistant',opendrinks:'Open Drinks',iba_community:'IBA 社区旧版'};
const states={missing:'缺少',quantity_needed:'待补用量',in_range:'在试配范围内',low:'相对偏少',high:'相对偏多'};
const originNames={kept:'保留你的用量',quantity_completed:'补充用量',pantry:'使用现有材料',shopping:'需要补充'};
function note(message,error=false){$('notice').innerHTML=message?`<div class="notice-box ${error?'error':''}">${esc(message)}</div>`:'';}
function readStorage(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}
function saveStorage(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{note('浏览器存储不可用，当前内容尚未保存。',true);return false;}}
async function api(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const result=await response.json();if(!response.ok)throw Error(result.error||'请求失败');return result;}
function link(url,label){try{const u=new URL(url);if(!['https:','http:'].includes(u.protocol))return esc(label);return `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;}catch{return esc(label);}}
function sources(urls){return `<div class="source-links">${urls.map(u=>link(u,'↗ '+u.split('/').filter(Boolean).at(-1).replaceAll('-',' '))).join('')}</div>`;}
function nameOf(id){return data.ingredients.find(i=>i.id===id)?.zh||id;}
function frame(){return data.frameworks.find(f=>f.id===frameId);}
function snapshot(){return {frame:frameId,recipe:$('recipe').value,pantry:$('pantry').value,avoid:$('avoid').value,method:$('method').value,preference:$('preference').value,context:judgeContext()};}
function storeDraft(){saveStorage('cocktail-draft-v1',snapshot());}
function view(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav').forEach(v=>{v.classList.toggle('active',v.dataset.view===id);v.setAttribute('aria-current',v.dataset.view===id?'page':'false');});if(id==='notebook')renderNotes();}
function setFrame(id,clearResult=true){frameId=id;const f=frame();$('frame-en').textContent=f.en.toUpperCase();$('frame-title').textContent=f.zh;$('formula').textContent=f.formula;$('frame-description').textContent=f.description;$('frame-note').textContent=f.note;$('frame-technique').textContent=f.methods.map(m=>data.methods[m]).join(' / ');$('frame-sources').innerHTML=sources(f.source_urls);document.querySelectorAll('.framework-button').forEach(b=>{b.classList.toggle('active',b.dataset.id===id);b.setAttribute('aria-pressed',String(b.dataset.id===id));});if(clearResult){$('result').innerHTML='<div class="empty-state"><h3>结构已切换</h3><p>当前输入已保留。重新评价，或填入新框架示例。</p></div>';lastEvaluation=null;lastDraft=null;}$('method').value=f.methods[0];}
function example(){const f=frame();$('recipe').value=f.slots.map(s=>`${nameOf(s.default)} ${s.amount}${units[s.unit]||s.unit}`).join('\n');$('method').value=f.methods[0];storeDraft();note('已填入框架试配示例；可按手边材料修改。');}
function renderRecognition(items){return `<div class="recognition">${items.map(i=>`<span class="ingredient-chip ${i.status==='matched'?'':'warning'}">${esc(i.status==='matched'?i.ingredient.zh:i.name+' · '+(i.status==='ambiguous'?'有歧义':'未识别'))}</span>`).join('')}</div>`;}
function evaluationHTML(r){return `<div class="score-top"><div class="score-ring"><b>${r.score??'—'}</b><small>${r.score===null?'暂不评分':'/ 100'}</small></div><div><h3>${esc(r.score_label)}</h3><p>${esc(r.confidence)}</p><p>不是“好喝程度”评分</p></div></div><div class="result-section">${renderRecognition(r.items)}</div><div class="result-section"><h4>这杯酒的结构</h4>${r.checks.map(c=>`<div class="check"><div class="check-title"><span>${esc(c.label)}</span><small>${states[c.state]||esc(c.state)}${c.value!==null?' · '+esc(Math.round(c.value*10)/10)+' '+esc(units[c.unit]||c.unit):''}</small></div><div class="bar"><i class="${c.fit<1?'warn':''}" style="width:${Math.max(0,Math.min(100,c.fit*100))}%"></i></div></div>`).join('')}</div>${r.suggestions.length?`<div class="result-section"><h4>可以怎么调整</h4><ul class="recommendations">${r.suggestions.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div>`:'<p class="fine">核心槽位齐全，比例在当前框架的试配范围内。接下来交给实际试饮。</p>'}${r.items.filter(i=>i.status!=='matched'&&i.choices?.length).map(i=>`<p class="fine">${esc(i.name)} 可确认：${i.choices.map(c=>esc(c.zh)).join(' / ')}。请修改输入后重试。</p>`).join('')}<details class="evidence"><summary>评分怎么算？</summary><p>${esc(r.score_explanation)}</p><p>糖浆槽位以原味糖浆的启发式甜味当量计，不是糖分克数；源材料浓度未知时仍需试饮。</p></details>${r.nearest_classics.length?`<div class="result-section"><h4>值得对照的经典配方</h4>${r.nearest_classics.map(c=>`<div class="classic"><strong>${link(c.source_url,c.name_zh||c.name)}</strong><small>${esc(c.name)} · 已识别原料重合 ${c.ingredient_overlap}%</small></div>`).join('')}<p class="fine">按原料类别重合度排序，未比较真实口味。</p></div>`:''}<div class="result-section">${sources(r.sources)}</div>`;}
function recipeText(lines,scale=1){return lines.map(i=>`${i.display_name||nameOf(i.name)}${i.amount!==null&&i.amount!==undefined?' '+Math.round(i.amount*scale*100)/100+(units[i.unit]||i.unit):''}`).join('\n');}
function resultButtons(){return '<div class="draft-actions"><button id="save-note" class="secondary">保存到试饮手记</button></div>';}
async function evaluate(){await perform(async()=>{const snap=snapshot();const r=await api('/api/evaluate',snap);lastEvaluation=r;lastDraft=null;lastSnapshot=snap;$('result').innerHTML=evaluationHTML(r)+resultButtons();bindSave();storeDraft();});}
async function complete(){await perform(async()=>{const snap=snapshot();const r=await api('/api/complete',snap);if(r.blocked){$('result').innerHTML=`<div class="empty-state"><h3>还需要确认一点</h3><p>${esc(r.reason)}</p>${r.unresolved?renderRecognition(r.unresolved):''}${r.unresolved?.map(i=>`<p class="fine">${esc(i.name)}：${i.choices?.map(c=>esc(c.zh)).join(' / ')||'请提供品类或明确名称'}</p>`).join('')||''}</div>`;lastDraft=null;lastEvaluation=null;return;}lastDraft=r;lastEvaluation=r.evaluation;lastSnapshot=snap;$('result').innerHTML=`<div class="frame-head"><h3>你的试配草案</h3><span class="pill">${esc(frame().zh)}</span></div><div>${r.recipe.map(i=>`<div class="draft-row"><span>${esc(i.display_name)}<small>${originNames[i.origin]}</small></span><b>${i.amount!==null?esc(i.amount)+' '+esc(units[i.unit]||i.unit):'按需'}</b></div>`).join('')}</div>${r.shopping.length?`<div class="shopping"><strong>需要补充 ${r.shopping.length} 种材料</strong><br>${r.shopping.map(i=>esc(i.display_name)).join('、')}</div>`:'<p class="fine">核心结构已用现有材料补齐。仍需冰块与相应器具。</p>'}<div class="result-section"><h4>怎么做 · ${esc(data.methods[r.method])}</h4><ol class="steps">${r.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></div><div class="draft-actions"><button id="use-draft" class="primary">采用这份草案</button><button id="copy-draft" class="secondary">复制配方</button></div><div class="settings-row"><label class="fine">份数<input id="servings" type="number" min="0.25" max="20" step="0.25" value="1"></label><button id="scale-draft" class="text-button">按份数填入配方 ↗</button></div><details class="evidence"><summary>补全依据与限制</summary><ul class="recommendations">${[...r.changes,...r.notes].map(n=>`<li>${esc(n)}</li>`).join('')}</ul>${r.unresolved_pantry.length?renderRecognition(r.unresolved_pantry):''}${sources(r.sources)}</details><details class="evidence"><summary>草案的框架检查（非独立试饮验证）</summary>${evaluationHTML(r.evaluation)}</details>${resultButtons()}`;$('use-draft').onclick=()=>{applyDraft(1);};$('scale-draft').onclick=()=>{const n=Number($('servings').value);if(!Number.isFinite(n)||n<.25||n>20)return note('份数需在 0.25–20 之间。',true);applyDraft(n);};$('copy-draft').onclick=async()=>{try{await navigator.clipboard.writeText(recipeText(r.recipe));note('配方已复制。');}catch{note('无法访问剪贴板；可先采用草案，再从输入框复制。',true);}};bindSave();storeDraft();});}
function applyDraft(scale){$('recipe').value=recipeText(lastDraft.recipe,scale);$('method').value=lastDraft.method;storeDraft();note(`已填入 ${scale} 份草案。比例缩放不等于原料余量核算，调制时建议分杯处理。`);}
function bindSave(){
 bindJudge();
 if(lastDraft?.alternatives){
  const section=document.createElement('details');section.className='evidence';
  section.innerHTML=`<summary>还可以尝试哪些配料？</summary><p class="fine">按结构角色推荐，不代表等味或等量替换；糖浆、橙酒与基酒换品后都需重新试配。</p><ul class="recommendations">${lastDraft.alternatives.map(a=>`<li><strong>${esc(a.slot)}</strong>：${a.options.map(o=>esc(o.name)+(o.in_pantry?'（已有）':'')).join(' / ')||'当前条件下无其他候选'}</li>`).join('')}</ul><p class="fine">可选点缀：${lastDraft.optional.map(i=>esc(i.zh)).join('、')||'先从核心结构开始'}</p>`;
  $('save-note').parentElement.before(section);
 }
 $('save-note').onclick=()=>{const notes=readStorage('cocktail-notes-v1',[]);const snap=lastSnapshot;const text=lastDraft?recipeText(lastDraft.recipe):snap.recipe;notes.unshift({id:crypto.randomUUID(),created:new Date().toISOString(),frame:snap.frame,recipe:text,method:lastDraft?.method||snap.method,score:lastEvaluation?.score,note:'',draft:!!lastDraft});if(saveStorage('cocktail-notes-v1',notes))note('已保存到「试饮手记」，可在那里记录酸甜感受。');};
}
async function perform(action){if(busy)return;busy=true;document.querySelectorAll('#evaluate,#complete,#pantry-search').forEach(b=>b.disabled=true);note('');try{await action();}catch(e){note(e.message,true);}finally{busy=false;document.querySelectorAll('#evaluate,#complete,#pantry-search').forEach(b=>b.disabled=false);}}
function renderDictionary(){const q=$('dictionary-search').value.toLocaleLowerCase().trim();const found=data.ingredients.filter(i=>[i.id,i.zh,i.en,i.brand,...i.aliases].some(v=>String(v||'').toLocaleLowerCase().includes(q)));$('dictionary-results').innerHTML=found.length?found.map(i=>`<article class="ingredient-card"><h3>${esc(i.zh)}</h3><p class="en">${esc(i.en)}</p><span class="pill">${i.brand?'品牌 / 产品':'原料类别'}</span>${i.parent?`<span class="pill">属于 ${esc(nameOf(i.parent))}</span>`:''}<p>别名：${i.aliases.length?i.aliases.map(esc).join(' / '):'使用上方中英文名称'}</p>${i.note?`<p>${esc(i.note)}</p>`:''}<button class="text-button dictionary-add" data-id="${esc(i.id)}">＋ 放进我的材料架</button></article>`).join(''):'<p class="fine">尚未收录这个名称。可以先输入明确的品类，如白朗姆、干味美思。</p>';document.querySelectorAll('.dictionary-add').forEach(b=>b.onclick=()=>{const names=$('pantry').value.trim();$('pantry').value=names?names+'、'+nameOf(b.dataset.id):nameOf(b.dataset.id);storeDraft();note('已加入材料架：'+nameOf(b.dataset.id));});}
function amountLabel(i){return i.amount_ml!==null?`${i.amount_ml} ml`:[i.amount_raw,i.unit].filter(x=>x!==null&&x!==undefined&&x!=='').join(' ')||'原文未给出确定用量';}
async function renderCompare(){try{const r=await api('/api/compare?name='+encodeURIComponent($('compare-select').value));const versions=[...r.versions].sort((a,b)=>(b.dataset==='iba_official')-(a.dataset==='iba_official'));if(!versions.length){$('comparison-result').textContent='未找到配方。';return;}$('comparison-result').innerHTML=`<p class="fine">${versions.length} 个来源版本。相同原料的品牌表达仍单独保留；未注明美制或英制的 oz 不转换为 ml。</p><div class="comparison-scroll"><table class="comparison-table"><thead><tr><th>对照项</th>${versions.map(v=>`<th>${esc(datasetNames[v.dataset]||v.dataset)}<small>${esc(v.name)} · ${link(v.source_url,'查看来源 ↗')}</small></th>`).join('')}</tr></thead><tbody><tr><td>原料与用量</td>${versions.map(v=>`<td><ul>${v.ingredients.map(i=>`<li>${esc(i.canonical_name_zh||i.original.name||'未拆分原料')} · ${esc(amountLabel(i))}${i.brand?`<small>品牌：${esc(i.brand)} / 类别：${esc(nameOf(i.category_id))}</small>`:''}<small>原始名称：${esc(i.original.name||JSON.stringify(i.original.raw))}</small>${i.status!=='matched'?'<small>待确认名称</small>':''}</li>`).join('')}</ul></td>`).join('')}</tr><tr><td>制作方法</td>${versions.map(v=>`<td>${esc(Array.isArray(v.instructions)?v.instructions.join('\n'):v.instructions||'来源未提供')}</td>`).join('')}</tr><tr><td>杯型 / 装饰</td>${versions.map(v=>`<td>${esc(v.glass||'杯型未单列')}<br>${esc(v.garnish||'装饰未单列')}</td>`).join('')}</tr></tbody></table></div><p class="fine">${r.comparison?`以 ${esc(versions.find(v=>v.id===r.comparison.reference_id)?.name||'首个版本')} 的${r.comparison.reference_reason==='IBA official'?'官方来源':'首个可用来源（无权威暗示）'}作为机器差异参照。已记录 ${r.comparison.differences.reduce((n,d)=>n+d.ingredient_differences.length,0)} 项原料表达或用量差异。`:''}用量差异不自动判为错误，原文制作方法尚未批量翻译。</p>`;}catch(e){note(e.message,true);}}
async function pantrySearch(){await perform(async()=>{const r=await api('/api/pantry',{pantry:$('pantry').value});$('pantry-result').innerHTML=`<p class="fine">${esc(r.scope)}</p>${renderRecognition(r.items)}<ul class="compact-list">${r.recipes.slice(0,12).map(c=>`<li>${link(c.source_url,c.name_zh||c.name)} · ${c.missing.length?'还差 '+esc(nameOf(c.missing[0])):'核心材料已齐'}</li>`).join('')||'<li>还没有材料齐全或只差一种的经典配方。</li>'}</ul>${r.shopping_priority.length?'<h4 class="fine">补充一种材料的优先参考</h4><ul class="compact-list">'+r.shopping_priority.map(s=>`<li>${esc(s.name)} · 可补齐 ${s.unlocks} 个配方的核心材料</li>`).join('')+'</ul>':''}`;storeDraft();});}
function renderNotes(){renderTrialHistory();const notes=readStorage('cocktail-notes-v1',[]);$('notebook-results').innerHTML=notes.length?notes.map(n=>`<article class="panel note-card"><h3>${esc(data.frameworks.find(f=>f.id===n.frame)?.zh||n.frame)}</h3><p class="fine">${esc(new Date(n.created).toLocaleString())} · 框架分 ${n.score??'未评分'}${n.draft?' · 补全草案':''}</p><pre>${esc(n.recipe)}</pre><label class="fine" for="note-${n.id}">试饮记录：酸甜、香气、融冰、下次调整</label><textarea id="note-${n.id}" data-note-id="${n.id}" rows="3" placeholder="例如：第一口偏甜，融冰后更舒服；下次糖浆减 3ml。">${esc(n.note)}</textarea><div class="note-tools"><button class="text-button reload-note" data-id="${n.id}">载入工作台 ↗</button><button class="text-button delete-note" data-id="${n.id}">删除这条手记</button></div></article>`).join(''):'<div class="panel empty-state"><h3>还没有试饮手记</h3><p>完成一次配方评价或补全后，点击「保存到试饮手记」。</p></div>';document.querySelectorAll('[data-note-id]').forEach(t=>t.oninput=()=>{const current=readStorage('cocktail-notes-v1',[]);const n=current.find(n=>n.id===t.dataset.noteId);if(n){n.note=t.value;saveStorage('cocktail-notes-v1',current);}});document.querySelectorAll('.reload-note').forEach(b=>b.onclick=()=>{const n=notes.find(n=>n.id===b.dataset.id);setFrame(n.frame);$('recipe').value=n.recipe;$('method').value=n.method;view('studio');storeDraft();note('手记配方已载入，可继续调整。');});document.querySelectorAll('.delete-note').forEach(b=>b.onclick=()=>{saveStorage('cocktail-notes-v1',readStorage('cocktail-notes-v1',[]).filter(n=>n.id!==b.dataset.id));renderNotes();});}
async function init(){try{data=await api('/api/catalog');$('hero-stats').innerHTML=`<div class="stat"><b>${data.frameworks.length}</b><span>调酒框架</span></div><div class="stat"><b>${data.stats.canonical_ingredients}</b><span>原料与产品</span></div>`;$('framework-list').innerHTML=data.frameworks.map((f,i)=>`<button class="framework-button" data-id="${f.id}" aria-pressed="false"><span class="number">${String(i+1).padStart(2,'0')}</span><span><strong>${esc(f.zh)}</strong><small>${esc(f.en)}</small></span></button>`).join('');$('method').innerHTML+=[...Object.entries(data.methods)].map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('');$('ingredient-options').innerHTML=data.ingredients.map(i=>`<option value="${esc(i.zh)}">${esc(i.en)}</option>`).join('');$('compare-select').innerHTML=data.comparison_groups.sort((a,b)=>a.name.localeCompare(b.name)).map(g=>`<option value="${esc(g.name)}">${esc(g.name)} · ${g.versions} 个版本</option>`).join('');$('compare-select').value='Negroni';document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>view(b.dataset.view));document.querySelectorAll('.framework-button').forEach(b=>b.onclick=()=>{setFrame(b.dataset.id);storeDraft();});const saved=readStorage('cocktail-draft-v1',null);setFrame(data.frameworks.some(f=>f.id===saved?.frame)?saved.frame:'sour',false);if(saved){for(const k of ['recipe','pantry','avoid','method','preference'])if(typeof saved[k]==='string')$(k).value=saved[k];if(saved.context)restoreJudgeContext(saved.context);}else{$('pantry').value='波本威士忌、金酒、青柠汁、君度、苏打水';}$('load-example').onclick=example;$('clear-recipe').onclick=()=>{$('recipe').value='';storeDraft();};$('add-ingredient').onclick=()=>{const name=$('ingredient-add').value.trim();if(name){$('recipe').value+=($('recipe').value?'\n':'')+name;$('ingredient-add').value='';storeDraft();}};$('evaluate').onclick=evaluate;$('complete').onclick=complete;$('pantry-search').onclick=pantrySearch;$('compare-select').onchange=renderCompare;$('dictionary-search').oninput=renderDictionary;for(const id of ['recipe','pantry','avoid','method','preference'])$(id).addEventListener('input',storeDraft);$('example-balanced').onclick=()=>{setFrame('sour',false);example();evaluate();};$('example-sour').onclick=()=>{setFrame('sour',false);$('recipe').value='波本威士忌 45ml\n柠檬汁 60ml\n原味糖浆 5ml';evaluate();};renderDictionary();await renderCompare();}catch(e){note('加载失败：'+e.message+'。请确认服务已启动，且已运行数据对齐脚本。',true);}}
init();
