'use strict';
let labRecommendation=null, labRequest=null, labExperiment=null;
const metricNames={abv:'酒精浓度',sugar_g_l:'糖浓度',acid_g_l:'可滴定酸度'};
const intensityNames={sweet:'甜感',sour:'酸感',bitter:'苦感',alcohol_heat:'酒精刺激',aroma:'香气强度',body:'酒体厚度',carbonation:'气泡刺激',astringency:'涩感'};
const operationNames={add:'加入配方原料',add_water:'加水',shake:'摇和',stir:'搅拌',strain:'滤冰 / 粗滤',clarify:'整杯澄清',carbonate:'充气',serve:'出杯'};

function comparisonRequest(){const s=snapshot();return {frame:s.frame,recipe:s.recipe,pantry:s.pantry,avoid:s.avoid,method:s.method,context:s.context,taster:$('lab-taster').value.trim()||'local'};}
function measureText(v,unit){return v===null?'未知':esc(v)+' '+esc(unit);}
async function recommendSour(){
  view('lab');$('lab-status').textContent='正在比较配方与依据…';
  try{
    const request=comparisonRequest();const r=await api('/api/recommend',request);
    if(r.blocked){$('lab-status').textContent=r.reason;$('lab-candidates').innerHTML='';return;}
    labRequest=request;labRecommendation=r;
    $('lab-status').textContent=r.ranking_policy;
    $('lab-candidates').innerHTML=r.candidates.map(c=>`<article class="panel lab-card"><p class="eyebrow">${c.id==='reference'?'REFERENCE':'CONTROLLED CHANGE'}</p><h3>${esc(c.title)}</h3><pre>${esc(recipeText(c.snapshot.recipe))}</pre><p>${esc(c.tradeoff)}</p><dl class="lab-metrics">${Object.entries(c.composition_changes).map(([k,v])=>`<div><dt>${metricNames[k]}</dt><dd>${measureText(v.before,v.unit)} → ${measureText(v.after,v.unit)}<br><small>${esc(v.stage)}</small></dd></div>`).join('')}</dl><p class="fine">浓度为声明条件下的估算；资料不足留空。实际好喝程度待试饮。</p><details class="evidence"><summary>为什么考虑这一版</summary>${c.evaluation.judge.interactions.map(x=>`<p><strong>${esc(x.title)}</strong>：${esc(x.effect)}<br><small>${esc(x.conditions)}</small></p>`).join('')}<p>框架契合度 ${c.evaluation.score??'待确认'} /100</p>${evidenceLinks(c.evaluation.judge.sources)}<p class="fine">可追溯到 ${c.trace.nodes.length} 个实体与 ${c.trace.edges.length} 条关系。</p></details><div class="draft-actions"><button class="secondary lab-load" data-id="${esc(c.id)}">载入工作台</button>${c.id!=='reference'?`<button class="primary lab-plan" data-id="${esc(c.id)}">与原版做 A/B</button>`:''}</div></article>`).join('');
    $('lab-shopping').textContent=r.shopping.length?'需要补充：'+r.shopping.map(x=>x.display_name).join('、'):'核心材料已具备；请确认实际余量。';
    $('lab-personal').textContent=`相同参照与条件的有效比较：${r.personal_evidence.eligible_pairs} 组。${r.personal_evidence.scope}`;
    document.querySelectorAll('.lab-load').forEach(b=>b.onclick=()=>{const c=r.candidates.find(c=>c.id===b.dataset.id);setFrame('sour',false);$('recipe').value=recipeText(c.snapshot.recipe);$('method').value=c.snapshot.method;restoreJudgeContext(c.snapshot.context);storeDraft();view('studio');evaluate();});
    document.querySelectorAll('.lab-plan').forEach(b=>{const id=crypto.randomUUID();b.onclick=async()=>{b.disabled=true;try{const plan=await api('/api/experiment_create',{...request,candidate_id:b.dataset.id,request_id:id});if(plan.blocked)throw Error(plan.reason);renderExperiment(plan);await loadExperimentHistory();}catch(e){$('lab-status').textContent=e.message;}finally{b.disabled=false;}};});
    renderMaterials(r.candidates.find(c=>c.id==='reference').evaluation);
  }catch(e){$('lab-status').textContent=e.message;}
}

function renderMaterials(evaluation){
  const c=evaluation.judge.snapshot.context;
  const unique=[...new Map(evaluation.items.filter(i=>i.status==='matched').map(i=>[i.ingredient.id,i])).values()];
  // Match aliases via the ingredient objects returned by the engine on the next request.
  const lookup=(list,id)=>list.find(x=>x.name===id||data.ingredients.find(i=>i.id===id&&[i.zh,i.en,...i.aliases].includes(x.name)));
  $('lab-materials').innerHTML=unique.map(i=>{const id=i.ingredient.id,m=lookup(c.materials||[],id)||{},s=lookup(c.composition||[],id)||{};return `<fieldset class="lab-material" data-id="${esc(id)}"><legend>${esc(i.ingredient.zh)}</legend><div class="settings-row"><label>实际产品<input data-material="product_label" value="${esc(m.product_label||'')}" placeholder="按瓶标填写"></label><label>批次 / 制备编号<input data-material="batch" value="${esc(m.batch||'')}" placeholder="未知留空"></label><label>产品版本<input data-material="variant" value="${esc(m.variant||'')}" placeholder="市场 / 年份 / 规格"></label></div><div class="settings-row">${Object.entries(metricNames).map(([k,n])=>`<label>${n}（${k==='abv'?'% vol':'g/L'}）<input data-metric="${k}" type="number" min="0" max="${k==='abv'?100:k==='sugar_g_l'?1500:500}" step="any" value="${s[k]??''}" placeholder="未知留空"></label>`).join('')}</div><div class="settings-row"><label>数值依据<select data-basis><option value="">请选择</option><option value="measurement" ${s.basis==='measurement'?'selected':''}>实际测量</option><option value="label" ${s.basis==='label'?'selected':''}>瓶标 / 厂商资料</option><option value="assumption" ${s.basis==='assumption'?'selected':''}>明确的情景假设</option></select></label><label>依据说明<input data-source value="${esc(s.source||'')}" placeholder="测量方法、瓶标或假设理由"></label></div></fieldset>`;}).join('');
  $('lab-apply-materials').onclick=()=>{const context=structuredClone(evaluation.judge.snapshot.context);context.materials=[];context.composition=[];
    document.querySelectorAll('.lab-material').forEach(row=>{const material={name:row.dataset.id},spec={name:row.dataset.id};row.querySelectorAll('[data-material]').forEach(x=>{if(x.value.trim())material[x.dataset.material]=x.value.trim();});if(Object.keys(material).length>1)context.materials.push(material);row.querySelectorAll('[data-metric]').forEach(x=>{if(x.value!=='')spec[x.dataset.metric]=Number(x.value);});if(Object.keys(spec).length>1){spec.basis=row.querySelector('[data-basis]').value;spec.source=row.querySelector('[data-source]').value;context.composition.push(spec);}});
    const ref=labRecommendation.candidates.find(c=>c.id==='reference');setFrame('sour',false);$('recipe').value=recipeText(ref.snapshot.recipe);$('method').value=ref.snapshot.method;restoreJudgeContext(context);storeDraft();recommendSour();};
}

function renderExperiment(record,history=null){
  labExperiment=record;const p=record.input;
  $('lab-trial').innerHTML=`<div class="page-heading"><p class="eyebrow">A / B · ONE CHANGE, TWO POURS</p><h3>先按 A → B 顺序品尝，再记录偏好</h3><p>顺序已随机分配。这是公开配方对照，并非盲评；每次新制作请创建新计划。</p><p class="fine">品鉴者：${esc(p.taster)} · ${esc(new Date(record.created_at).toLocaleString())}${p.data_kind==='synthetic'?' · 合成演示，不参与偏好':''}</p></div><div class="lab-grid">${p.samples.map(s=>`<article class="panel lab-sample" data-serving="${esc(s.serving_id)}"><h3>样品 ${esc(s.code)}</h3><pre>${esc(recipeText(s.snapshot.recipe))}</pre><p>${esc(s.tradeoff)}</p><label class="check-label"><input type="checkbox" data-tasted> 我已实际调制并试饮此杯</label><label class="check-label"><input type="checkbox" data-as-planned> 实际用量与计划一致</label><label>品尝时间点<select data-timepoint><option value="0">第一口（0 秒）</option><option value="120">放置 2 分钟后</option></select></label><details class="evidence"><summary>感官强度（与质量分开）</summary><div class="rating-inputs">${Object.entries(intensityNames).map(([id,n])=>`<label>${n}<input data-intensity="${id}" type="number" min="0" max="10" step=".5" placeholder="0–10，未评留空"></label>`).join('')}</div></details><details class="evidence"><summary>七维质量（未评留空）</summary><div class="rating-inputs">${[['appearance','外观'],['aroma','香气'],['balance','平衡'],['structure','层次'],['texture','口感'],['execution','执行'],['expression','表达']].map(([id,n])=>`<label>${n}<input data-rating="${id}" type="number" min="0" max="10" step=".5" placeholder="0–10"></label>`).join('')}</div></details><label>整体喜欢程度<input type="number" min="0" max="10" step=".5" data-liking placeholder="0–10，未评留空"></label><label>此时实测温度（℃）<input data-observation-temperature type="number" min="-30" max="100" step=".1" placeholder="未知留空"></label><label>实际制作条件与偏离<textarea data-deviations rows="2" placeholder="若温度、融水或原料不同，请说明；该组不会参与偏好排序。"></textarea></label><label>品尝记录<textarea data-notes rows="2" placeholder="入口、中段、余韵"></textarea></label><button class="primary lab-observe">保存这一杯的观察</button><p class="fine lab-observe-status" role="status"></p></article>`).join('')}</div><div class="panel"><h3>同一时间点，哪一杯更合意？</h3><div class="settings-row"><label>比较时间点<select id="lab-choose-time"><option value="0">第一口</option><option value="120">2 分钟后</option></select></label><label>偏好<select id="lab-choice"><option value="A">A</option><option value="B">B</option><option value="tie">差不多</option><option value="inconclusive">无法判断</option></select></label></div><button id="lab-save-choice" class="primary">保存这次比较</button><p id="lab-choice-status" role="status"></p></div>`;
  document.querySelectorAll('.lab-sample').forEach(row=>{let token=crypto.randomUUID(),lastBody=null;row.querySelector('.lab-observe').onclick=async()=>{const status=row.querySelector('.lab-observe-status');if(!row.querySelector('[data-as-planned]').checked){status.textContent='实际配方不同，请在工作台另建计划；接口也支持单独记录实际配方。';return;}
    const tasting={tasted:row.querySelector('[data-tasted]').checked,ratings:{},notes:row.querySelector('[data-notes]').value,taster:p.taster},observation={as_planned:true,timepoint_s:Number(row.querySelector('[data-timepoint]').value),intensities:{},deviations:row.querySelector('[data-deviations]').value};
    row.querySelectorAll('[data-rating]').forEach(x=>{if(x.value!=='')tasting.ratings[x.dataset.rating]=Number(x.value);});row.querySelectorAll('[data-intensity]').forEach(x=>{if(x.value!=='')observation.intensities[x.dataset.intensity]=Number(x.value);});if(row.querySelector('[data-liking]').value!=='')tasting.overall_liking=Number(row.querySelector('[data-liking]').value);
    if(row.querySelector('[data-observation-temperature]').value!=='')observation.temperature_c=Number(row.querySelector('[data-observation-temperature]').value);
    const body={experiment_id:record.id,serving_id:row.dataset.serving,tasting,observation};if(lastBody!==JSON.stringify(body)){token=crypto.randomUUID();lastBody=JSON.stringify(body);}try{await api('/api/experiment_observe',{...body,request_id:token});status.textContent='已保存在本地。两杯都记录后，可以比较偏好。';}catch(e){status.textContent=e.message;}};});
  let choiceToken=crypto.randomUUID(),choiceBody='';$('lab-save-choice').onclick=async()=>{const b={experiment_id:record.id,preferred:$('lab-choice').value,timepoint_s:Number($('lab-choose-time').value)};if(choiceBody!==JSON.stringify(b)){choiceToken=crypto.randomUUID();choiceBody=JSON.stringify(b);}try{await api('/api/experiment_choose',{...b,request_id:choiceToken});$('lab-choice-status').textContent='已保存；下一次比较候选时会读取相同条件的有效记录。';await loadExperimentHistory();}catch(e){$('lab-choice-status').textContent=e.message;}};
  if(history){
    const observations=history.observations.filter(o=>o.input.experiment_id===record.id),replaced=new Set(observations.map(o=>o.input.supersedes));
    const result=history.results.find(r=>r.input.experiment_id===record.id);
    const summary=document.createElement('div');summary.className='panel';summary.innerHTML='<h3>已保存的观察</h3>'+observations.map(o=>{const p=o.input,sample=record.input.samples.find(s=>s.serving_id===p.serving_id);return `<p>样品 ${esc(sample?.code)} · ${p.timepoint_s} 秒 · 喜欢程度 ${p.sensory.overall_liking??'未评'}/10${replaced.has(o.id)?' · 已被更正':''}</p><p class="fine">${Object.entries(p.intensities).map(([k,v])=>esc(intensityNames[k])+' '+v).join(' · ')} ${esc(p.tasting.notes||'')}</p>`;}).join('')+(result?`<p>最近比较：${esc(result.input.preferred)} · ${result.input.timepoint_s} 秒。更正观察后请重新比较。</p>`:'');
    $('lab-trial').append(summary);
  }
  $('lab-trial').scrollIntoView({behavior:'smooth',block:'start'});
}

async function loadExperimentHistory(){
  try{const h=await api('/api/experiment_history',{});$('lab-history').innerHTML=h.experiments.length?h.experiments.map(e=>`<button class="secondary lab-reopen" data-id="${esc(e.id)}">${esc(e.input.taster)} · ${esc(new Date(e.created_at).toLocaleString())} · 载入试验</button>`).join(' '):'<p class="fine">还没有 A/B 计划。先比较候选，再选择一个改版。</p>';document.querySelectorAll('.lab-reopen').forEach(b=>b.onclick=()=>renderExperiment(h.experiments.find(e=>e.id===b.dataset.id),h));}catch(e){$('lab-history').textContent=e.message;}
}
document.addEventListener('DOMContentLoaded',()=>{$('recommend-sour').onclick=recommendSour;$('lab-recommend').onclick=recommendSour;$('lab-refresh-history').onclick=loadExperimentHistory;});
